apiVersion: netwokring.k8s.io/v1
kind: Ingress
metadata:
  name: goweb
spec:
  rules:
  - host: webapp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
          name: go-webapp
          port:
            number: 8080